### ISSUE TITLE
creating catmux sessions breaks with version 0.3.4?

### ISSUE THREAD

**Issue by develNor** [fmauch/catmux#30]
the command `catmux_create_session example_session.yaml` throws the error
```
no server running on /tmp/tmux-1000/catmux
Using tmux config file: /home/myuser/.local/lib/python3.8/site-packages/catmux/resources/tmux_default.conf
Traceback (most recent call last):
  File "/home/myuser/.local/bin/catmux_create_session", line 142, in <module>
    main()
  File "/home/myuser/.local/bin/catmux_create_session", line 130, in main
    print(" ".join(command))
TypeError: sequence item 4: expected str instance, PosixPath found
```
This happens only with the latest version (`0.3.4`)
I used a docker container with Ubuntu 20.04.

**Comment by fmauch** [comment]
Thank you for the report, I'll have to investigate this.

**Comment by fmauch** [comment]
Confirmed locally.
